### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by orangemug** [eleith/schemajs#17]
Can we get a new version published to npm (https://www.npmjs.com/package/schemajs). The last version was published 10months ago.

Note: You can setup auto deploy via travis on version tag. I've got that setup here, if you need a reference https://github.com/orangemug/sql-stamp/blob/master/.travis.yml#L7...L13

**Comment by eleith** [comment]
done

**Comment by orangemug** [comment]
Thanks!
