### ISSUE TITLE
Should it also handle "PUT" and "DELETE"? 

### ISSUE THREAD

**Issue by murvinlai** [eleith/schemajs#20]
in the lib/schema.js,  it takes & validates the req.body if it is POST, or else req.query. 

however, should it validate the req.body for PUT and DELETE instead of req.query? 

or in general, should it just take input from both req.body & req.query regardless of the method? 

or take req.body by default, and take req.query if req.body is empty..

**Comment by eleith** [comment]
good point.

i'm considering removing the middleware from this library though and just leaving it as comments so that this library can remain focused purely on schema validation and middleware can be handled by others

**Comment by murvinlai** [comment]
or how about having an init function that allows custom functions passing in, otherwise, use the default logic inside the middleware. :)
